<a href="https://colab.research.google.com/github/niweshkumarsuman/DMDW-Lab/blob/main/12_10_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3])
print(type(a))
print(a)
b=np.array(([1,2],[3,4]))
print(b)
print(b.shape)
print(a.shape)
c=np.zeros((3,3))
print(c)
d=np.ones((3,3))
print(d)
e=np.random.random((3,3))
print(e)
i=np.eye(3)
print(i)
j=np.arange(20)
print(j)
print(j[1:7:2])
print(j[5:15:3])
print(j[-1:5:-2])
k=np.array([[12,11],[9,7],[5,13]])
print(k.shape)
print(k>10)

In [ ]:
l=np.random.random((3,2))
print(l.shape)
print(l)
print(k+l)
print(k-l)
x=np.sum(k,axis=0)
y=np.sum(k,axis=1)
print(y)
print(x)


In [ ]:
p=np.array([[12,11,5],[9,7,3]])
print(p)
w=np.array([1.0,1.1])
print(w)
#print(p+w)
print((p.T+w).T)

[[12 11  5]
 [ 9  7  3]]
[1.  1.1]
[[13.  12.   6. ]
 [10.1  8.1  4.1]]
